 import 'package:biteflow/models/order_item.dart';

List<OrderItem> orderedItemsData = [
  OrderItem(
    id: '1',
    title: 'Chicken Biryani',
    price: 12.99,
    imageUrl: 'https://tse1.mm.bing.net/th?id=OIP.cYyial3SHy3GYgXblu8qEQHaDu&w=238&h=238&c=7',
    description: 'Delicious spicy chicken biryani.',
    rating: 0.0,
    quantity: 1,
    notes: 'Extra spicy',
  ),
  OrderItem(
    id: '2',
    title: 'Paneer Butter Masala',
    price: 10.99,
    imageUrl: 'https://tse1.mm.bing.net/th?id=OIP.qs-kHwa4ROJW_cjnQsoL8wHaJ3&w=474&h=474&c=7',
    description: 'Creamy paneer butter masala.',
    rating: 0.0,
    quantity: 2,
    notes: '',
  ),
   OrderItem(
    id: '2',
    title: 'Paneer Butter Masala',
    price: 10.99,
    imageUrl: 'https://tse1.mm.bing.net/th?id=OIP.qs-kHwa4ROJW_cjnQsoL8wHaJ3&w=474&h=474&c=7',
    description: 'Creamy paneer butter masala.',
    rating: 0.0,
    quantity: 2,
    notes: '',
  ),
   OrderItem(
    id: '2',
    title: 'Paneer Butter Masala',
    price: 10.99,
    imageUrl: 'https://tse1.mm.bing.net/th?id=OIP.qs-kHwa4ROJW_cjnQsoL8wHaJ3&w=474&h=474&c=7',
    description: 'Creamy paneer butter masala.',
    rating: 0.0,
    quantity: 2,
    notes: '',
  ),
   OrderItem(
    id: '2',
    title: 'Paneer Butter Masala',
    price: 10.99,
    imageUrl: 'https://tse1.mm.bing.net/th?id=OIP.qs-kHwa4ROJW_cjnQsoL8wHaJ3&w=474&h=474&c=7',
    description: 'Creamy paneer butter masala.',
    rating: 0.0,
    quantity: 2,
    notes: '',
  ),
   OrderItem(
    id: '2',
    title: 'Paneer Butter Masala',
    price: 10.99,
    imageUrl: 'https://tse1.mm.bing.net/th?id=OIP.qs-kHwa4ROJW_cjnQsoL8wHaJ3&w=474&h=474&c=7',
    description: 'Creamy paneer butter masala.',
    rating: 0.0,
    quantity: 2,
    notes: '',
  ),
   OrderItem(
    id: '2',
    title: 'Paneer Butter Masala',
    price: 10.99,
    imageUrl: 'https://tse1.mm.bing.net/th?id=OIP.qs-kHwa4ROJW_cjnQsoL8wHaJ3&w=474&h=474&c=7',
    description: 'Creamy paneer butter masala.',
    rating: 0.0,
    quantity: 2,
    notes: '',
  ),
   OrderItem(
    id: '2',
    title: 'Paneer Butter Masala',
    price: 10.99,
    imageUrl: 'https://tse1.mm.bing.net/th?id=OIP.qs-kHwa4ROJW_cjnQsoL8wHaJ3&w=474&h=474&c=7',
    description: 'Creamy paneer butter masala.',
    rating: 0.0,
    quantity: 2,
    notes: '',
  ),
   OrderItem(
    id: '2',
    title: 'Paneer Butter Masala',
    price: 10.99,
    imageUrl: 'https://tse1.mm.bing.net/th?id=OIP.qs-kHwa4ROJW_cjnQsoL8wHaJ3&w=474&h=474&c=7',
    description: 'Creamy paneer butter masala.',
    rating: 0.0,
    quantity: 2,
    notes: '',
  ),
   OrderItem(
    id: '2',
    title: 'Paneer Butter Masala',
    price: 10.99,
    imageUrl: 'https://tse1.mm.bing.net/th?id=OIP.qs-kHwa4ROJW_cjnQsoL8wHaJ3&w=474&h=474&c=7',
    description: 'Creamy paneer butter masala.',
    rating: 0.0,
    quantity: 2,
    notes: '',
  ),
   OrderItem(
    id: '2',
    title: 'Paneer Butter Masala',
    price: 10.99,
    imageUrl: 'https://tse1.mm.bing.net/th?id=OIP.qs-kHwa4ROJW_cjnQsoL8wHaJ3&w=474&h=474&c=7',
    description: 'Creamy paneer butter masala.',
    rating: 0.0,
    quantity: 2,
    notes: '',
  ),
  
  // Add more items as needed
];
