// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlCUBAN8dHL5a8XbpnwGU3aPgyvpxhRHM',
    appId: '1:206872951763:web:5e3b4de42658e34963cd26',
    messagingSenderId: '206872951763',
    projectId: 'biteflow-e1515',
    authDomain: 'biteflow-e1515.firebaseapp.com',
    storageBucket: 'biteflow-e1515.firebasestorage.app',
    measurementId: 'G-X5V1TD656T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuUvmtv6kgihwW-bncUHlLv8lYiBEV0H0',
    appId: '1:206872951763:android:47938f1a0fe265f163cd26',
    messagingSenderId: '206872951763',
    projectId: 'biteflow-e1515',
    storageBucket: 'biteflow-e1515.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUoCPn3WMk9V6ADhpkzpNZBCkJBUDGoG8',
    appId: '1:206872951763:ios:c841adad3f17660a63cd26',
    messagingSenderId: '206872951763',
    projectId: 'biteflow-e1515',
    storageBucket: 'biteflow-e1515.firebasestorage.app',
    iosBundleId: 'com.example.biteflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUoCPn3WMk9V6ADhpkzpNZBCkJBUDGoG8',
    appId: '1:206872951763:ios:c841adad3f17660a63cd26',
    messagingSenderId: '206872951763',
    projectId: 'biteflow-e1515',
    storageBucket: 'biteflow-e1515.firebasestorage.app',
    iosBundleId: 'com.example.biteflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlCUBAN8dHL5a8XbpnwGU3aPgyvpxhRHM',
    appId: '1:206872951763:web:5af628ce9bd8731963cd26',
    messagingSenderId: '206872951763',
    projectId: 'biteflow-e1515',
    authDomain: 'biteflow-e1515.firebaseapp.com',
    storageBucket: 'biteflow-e1515.firebasestorage.app',
    measurementId: 'G-MQJTJHBDBR',
  );
}
