name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flutter:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Flutter (using your version 3.24.5)
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # (Optional) Build the APK for Android
      - name: Build APK
        run: flutter build apk --release

      # (Optional) Build the iOS app
      # - name: Build iOS
      #   run: flutter build ios --release
