name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flutter:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Run Flutter's static analysis tool (similar to ESLint)
      - name: Run Flutter analyze
        run: flutter analyze  

      # Run flutter doctor to ensure Flutter environment is properly set up
      - name: Run flutter doctor
        run: flutter doctor